# Test against the latest versions of this Node.js version
environment:
  matrix:
    # node.js
    - nodejs_version: "6"
    - nodejs_version: "7"

matrix:
  allow_failures:
    - nodejs_version: "7"
    - platform: "x86"

# Install scripts. (runs after repo cloning)
install:
  - git submodule update --init --recursive
  # Get the latest stable version of Node.js or io.js
  - ps: Install-Product node $env:nodejs_version
  # install modules
  - npm install

platform:
- x86
- x64

# Post-install test scripts.
test_script:
  - node --version
  - npm --version

build: off
